const { GoogleSpreadsheet } = require('google-spreadsheet');
var express = require('express');


var app = express();
// Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet('1sVMH3Xm_NLt4trNHtEnSiH89NcAdaM0iwsNQDwPMOaw');

// Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
await doc.useServiceAccountAuth({
  // env var values are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  client_email: "email do gabriel",
  private_key: "chave privada",
});

await doc.loadInfo(); // loads document properties and worksheets

const sheet = doc.sheetsByIndex[0];

const rows = await sheet.getRows(); // can pass in { limit, offset }

app.get('/', function (req, res) {
  res.send('Hello World!');
});

app.get('/sheets/:name', function (req, res) {
  let rows = await sheet.getRows();
  res.send(
    rows.filter((row) => {
      row["Nome completo do paciente"] === req.params.name
    })
  );
});

app.get('/sheets', function (req, res) {
  let rows = await sheet.getRows();
  res.send(
    rows
  );
});



app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
